### ISSUE TITLE
flex-volume support (for rancher >1.6.15 / k8s)

### ISSUE THREAD

**Issue by blaggacao** [camptocamp/conplicity#150] opened 2018-04-07 05:15 UTC
haven't looked deeper but as it says "named volume" in the docs I might smell a problem here..

**Comment by raphink** [comment] 2018-04-09 04:44
#139 should fix that in a proper way

**Comment by blaggacao** [comment] 2018-04-09 20:34
Or https://github.com/camptocamp/conplicity/pull/149?

**Comment by cryptobioz** [comment] 2018-04-10 06:43
The Kubernetes orchestrator (#149) backups all PVC, so, the volume type is transparent.

**Comment by mcanevet** [comment] 2018-04-20 14:30
Duplicate of #139 and #140

**Closed by mcanevet** 2018-04-20 14:30 UTC
